workflows:
  ios-workflow:
    name: Build and release iOS app
    environment:
      vars:
        XCODE_WORKSPACE: "TasbeehPlus.xcworkspace"
        XCODE_SCHEME: "TasbeehPlus"
        BUNDLE_ID: "com.sky.tasbeeh"
        APP_STORE_ID: "6744103046"
        DEVELOPMENT_TEAM: "BSFW4YJUKY"

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Set provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp TasbeehPlus_FinalProfile_2025.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build .ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
