workflows:
  ios-workflow:
    name: Build and release iOS app
    environment:
      vars:
        XCODE_PROJECT: "TasbeehPlus.xcodeproj"
        XCODE_SCHEME: "TasbeehPlus"
        BUNDLE_ID: "com.sky.tasbeeh"
        APP_STORE_ID: "6744103046"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build .ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store \
            --export-team-id BSFW4YJUKY
    artifacts:
      - build/ios/ipa/*.ipa
