default_platform(:ios)

platform :ios do
  desc "Upload build to the App Store"
  lane :release do
    build_app(
      scheme: "TasbeehPlus"
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
